# Site settings
title: kaku's blog
url: "http://funcallfunc.com"
baseurl: ""
description: >
  A maker and programmer

# Your information
email: rookit.cn@gmail.com
author: guofei
avatar: "//s.gravatar.com/avatar/1800b08b20f8b2a9aa3f5f23822bd4ad?d=mm&s=135"
profile: A maker and programmer
# twitter_username: twitter_username
github_username:  guofei
disqus_shortname: kakusblog
# permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
